# Generated by Django 4.1.2 on 2022-10-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название города')),
                ('slug', models.CharField(blank=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Язык программирования')),
                ('slug', models.CharField(blank=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
    ]
